/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRoom {
    #[serde(rename = "private_level")]
    pub private_level: models::RoomLevel,
    #[serde(
        rename = "invite",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub invite: Option<Option<Vec<models::CreateRoomInviteInner>>>,
    #[serde(
        rename = "key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub key: Option<Option<String>>,
}

impl CreateRoom {
    pub fn new(private_level: models::RoomLevel) -> CreateRoom {
        CreateRoom {
            private_level,
            invite: None,
            key: None,
        }
    }
}
