/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageSend {
    #[serde(rename = "content")]
    pub content: models::MessageType,

    #[serde(rename = "send_at")]
    pub send_at: DateTime<Utc>,

    #[serde(rename = "data", default, skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<Box<serde_json::Value>>>,
}
