/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRoom {
    #[serde(
        rename = "private_level",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub private_level: Option<Option<models::RoomLevel>>,
    #[serde(
        rename = "invite",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub invite: Option<Option<Vec<models::CreateRoomInviteInner>>>,
    #[serde(
        rename = "key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub key: Option<Option<String>>,
}

impl UpdateRoom {
    pub fn new() -> UpdateRoom {
        UpdateRoom {
            private_level: None,
            invite: None,
            key: None,
        }
    }
}
