/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserType {
    #[serde(rename = "GUEST")]
    Guest,
    #[serde(rename = "PERMANENT")]
    Permanent,
}

impl std::fmt::Display for UserType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Guest => write!(f, "GUEST"),
            Self::Permanent => write!(f, "PERMANENT"),
        }
    }
}

impl Default for UserType {
    fn default() -> UserType {
        Self::Guest
    }
}
