/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Content {
    #[serde(rename = "content_base64")]
    pub content_base64: String,
    #[serde(rename = "nonce")]
    pub nonce: String,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "public_key")]
    pub public_key: String,
    #[serde(rename = "encrypted_symmetric_key")]
    pub encrypted_symmetric_key: String,
    #[serde(rename = "check_msg")]
    pub check_msg: String,
    #[serde(rename = "sender_public_key")]
    pub sender_public_key: String,
    #[serde(rename = "online_users")]
    pub online_users: i32,
}

impl Content {
    pub fn new(content_base64: String, nonce: String, content: String, public_key: String, encrypted_symmetric_key: String, check_msg: String, sender_public_key: String, online_users: i32) -> Content {
        Content {
            content_base64,
            nonce,
            content,
            public_key,
            encrypted_symmetric_key,
            check_msg,
            sender_public_key,
            online_users,
        }
    }
}

