/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRoom {
    #[serde(rename = "private_level")]
    pub private_level: models::RoomLevel,
    #[serde(rename = "invite", deserialize_with = "Option::deserialize")]
    pub invite: Option<Vec<models::CreateRoomInviteInner>>,
    #[serde(rename = "key", deserialize_with = "Option::deserialize")]
    pub key: Option<String>,
}

impl CreateRoom {
    pub fn new(
        private_level: models::RoomLevel,
        invite: Option<Vec<models::CreateRoomInviteInner>>,
        key: Option<String>,
    ) -> CreateRoom {
        CreateRoom {
            private_level,
            invite,
            key,
        }
    }
}
