/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Encrypted {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "content_base64")]
    pub content_base64: String,
    #[serde(rename = "nonce")]
    pub nonce: String,
}

impl Encrypted {
    pub fn new(content_base64: String, nonce: String) -> Encrypted {
        Encrypted {
            r#type: None,
            content_base64,
            nonce,
        }
    }
}

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Type {
    #[serde(rename = "ENCRYPTED")]
    #[default]
    Encrypted,
}
