/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorModel {
    #[serde(rename = "detail")]
    pub detail: String,
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<String>,
}

impl ErrorModel {
    pub fn new(detail: String, id: Option<String>) -> ErrorModel {
        ErrorModel { detail, id }
    }
}
