/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Invite {
    #[serde(rename = "Username")]
    Username(models::InviteUsername),
    #[serde(rename = "UUID")]
    Uuid(models::InviteUuid),
}

impl Default for Invite {
    fn default() -> Self {
        Self::Username(Default::default())
    }
}
