/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InviteWrapper {
    //
    #[serde(rename = "invite")]
    pub invite: models::Invite,
}

impl InviteWrapper {
    pub fn new(invite: models::Invite) -> InviteWrapper {
        InviteWrapper { invite }
    }
}
