/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyResponse {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "encrypted_symmetric_key")]
    pub encrypted_symmetric_key: String,
    #[serde(rename = "check_msg")]
    pub check_msg: String,
    #[serde(rename = "sender_public_key")]
    pub sender_public_key: String,
    #[serde(rename = "nonce")]
    pub nonce: String,
}

impl KeyResponse {
    pub fn new(encrypted_symmetric_key: String, check_msg: String, sender_public_key: String, nonce: String) -> KeyResponse {
        KeyResponse {
            r#type: None,
            encrypted_symmetric_key,
            check_msg,
            sender_public_key,
            nonce,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "KEY_RESPONSE")]
    KeyResponse,
}

impl Default for Type {
    fn default() -> Type {
        Self::KeyResponse
    }
}

