/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageSend {
    #[serde(rename = "type")]
    pub r#type: models::MessageType,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<models::Content>,
    #[serde(rename = "send_at")]
    pub send_at: String,
    #[serde(
        rename = "data",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub data: Option<Option<serde_json::Value>>,
}

impl MessageSend {
    pub fn new(r#type: models::MessageType, send_at: String) -> MessageSend {
        MessageSend {
            r#type,
            content: None,
            send_at,
            data: None,
        }
    }
}
