/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum MessageSendContent {
    #[serde(rename="ENCRYPTED")]
    Encrypted(Box<models::Encrypted>),
    #[serde(rename="PLAINTEXT")]
    Plaintext(Box<models::Plaintext>),
    #[serde(rename="KEY_REQUEST")]
    KeyRequest(Box<models::KeyRequest>),
    #[serde(rename="KEY_RESPONSE")]
    KeyResponse(Box<models::KeyResponse>),
    #[serde(rename="SYSTEM")]
    System(Box<models::SystemMessage>),
}

impl Default for MessageSendContent {
    fn default() -> Self {
        Self::Encrypted(Default::default())
    }
}


