/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use strum::{Display, EnumIter};
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, EnumIter,
)] //, Display)]
#[derive(Default)]
pub enum MessageType {
    #[serde(rename = "ENCRYPTED")]
    #[strum(to_string = "ENCRYPTED")]
    #[default]
    Encrypted,
    #[serde(rename = "PLAINTEXT")]
    #[strum(to_string = "PLAINTEXT")]
    Plaintext,
    #[serde(rename = "KEY_REQUEST")]
    #[strum(to_string = "KEY_REQUEST")]
    KeyRequest,
    #[serde(rename = "KEY_RESPONSE")]
    #[strum(to_string = "KEY_RESPONSE")]
    KeyResponse,
    #[serde(rename = "SYSTEM")]
    #[strum(to_string = "SYSTEM")]
    System,
    #[serde(rename = "JOIN")]
    #[strum(to_string = "JOIN")]
    Join,
    #[serde(rename = "LEAVE")]
    #[strum(to_string = "LEAVE")]
    Leave,
}

impl std::fmt::Display for MessageType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Encrypted => write!(f, "ENCRYPTED"),
            Self::Plaintext => write!(f, "PLAINTEXT"),
            Self::KeyRequest => write!(f, "KEY_REQUEST"),
            Self::KeyResponse => write!(f, "KEY_RESPONSE"),
            Self::System => write!(f, "SYSTEM"),
            Self::Join => write!(f, "JOIN"),
            Self::Leave => write!(f, "LEAVE"),
        }
    }
}

