/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum MessageType {
    #[serde(rename = "ENCRYPTED")]
    Encrypted(models::Encrypted),
    #[serde(rename = "PLAINTEXT")]
    Plaintext(models::Plaintext),
    #[serde(rename = "KEY_REQUEST")]
    KeyRequest(models::KeyRequest),
    #[serde(rename = "KEY_RESPONSE")]
    KeyResponse(models::KeyResponse),
    #[serde(rename = "SYSTEM")]
    System(models::SystemMessage),
    #[serde(rename = "JOIN")]
    Join(models::SystemMessage),
    #[serde(rename = "LEAVE")]
    Leave(models::SystemMessage),
}

impl std::fmt::Display for MessageType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Encrypted(_) => write!(f, "ENCRYPTED"),
            Self::Plaintext(_) => write!(f, "PLAINTEXT"),
            Self::KeyRequest(_) => write!(f, "KEY_REQUEST"),
            Self::KeyResponse(_) => write!(f, "KEY_RESPONSE"),
            Self::System(_) => write!(f, "SYSTEM"),
            Self::Join(_) => write!(f, "JOIN"),
            Self::Leave(_) => write!(f, "LEAVE"),
        }
    }
}
