/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageSend {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::MessageType>,
    #[serde(rename = "content")]
    pub content: models::Content,
    #[serde(rename = "send_at")]
    pub send_at: String,
    #[serde(rename = "data", deserialize_with = "Option::deserialize")]
    pub data: Option<serde_json::Value>,
}

impl MessageSend {
    pub fn new(
        content: models::Content,
        send_at: String,
        data: Option<serde_json::Value>,
    ) -> MessageSend {
        MessageSend {
            r#type: None,
            content,
            send_at,
            data,
        }
    }
}
