/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagePublic {
    //
    #[serde(rename = "type")]
    pub r#type: models::MessageType,
    //
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<models::Content>,
    //
    #[serde(rename = "send_at")]
    pub send_at: String,
    //
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    // , deserialize_with = "Option::deserialize"
    #[serde(rename = "sender")]
    pub sender: models::UserPublic,
}

impl MessagePublic {
    pub fn new(
        r#type: models::MessageType,
        send_at: String,
        sender: models::UserPublic,
    ) -> MessagePublic {
        MessagePublic {
            r#type,
            content: None,
            send_at,
            data: None,
            sender,
        }
    }
}
