/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagePublic {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::MessageType>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<models::Content>,
    #[serde(rename = "send_at", skip_serializing_if = "Option::is_none")]
    pub send_at: Option<String>,
    #[serde(
        rename = "data",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub data: Option<Option<serde_json::Value>>,
    #[serde(rename = "sender", deserialize_with = "Option::deserialize")]
    pub sender: Option<models::UserPublic>,
}

impl MessagePublic {
    pub fn new(sender: Option<models::UserPublic>) -> MessagePublic {
        MessagePublic {
            r#type: None,
            content: None,
            send_at: None,
            data: None,
            sender,
        }
    }
}
