/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoomLevel {
    #[serde(rename = "FREE")]
    Free,
    #[serde(rename = "KEY")]
    Key,
    #[serde(rename = "INVITE-ONLY")]
    InviteOnly,
    #[serde(rename = "INVITE-AND-KEY")]
    InviteAndKey,

}

impl std::fmt::Display for RoomLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Free => write!(f, "FREE"),
            Self::Key => write!(f, "KEY"),
            Self::InviteOnly => write!(f, "INVITE-ONLY"),
            Self::InviteAndKey => write!(f, "INVITE-AND-KEY"),
        }
    }
}

impl Default for RoomLevel {
    fn default() -> RoomLevel {
        Self::Free
    }
}

