/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StaticRoomPublic {
    //
    #[serde(rename = "name")]
    pub name: String,
    // , deserialize_with = "Option::deserialize"
    #[serde(rename = "key")]
    pub key: Option<String>,
    //
    #[serde(rename = "id")]
    pub id: i32,
    //
    #[serde(rename = "owner")]
    pub owner: models::UserPublic,
    //
    #[serde(rename = "users")]
    pub users: Vec<models::UserPublic>,
    //
    #[serde(rename = "level")]
    pub level: models::RoomLevel,
}

impl StaticRoomPublic {
    pub fn new(
        name: String,
        key: Option<String>,
        id: i32,
        owner: models::UserPublic,
        users: Vec<models::UserPublic>,
        level: models::RoomLevel,
    ) -> StaticRoomPublic {
        StaticRoomPublic {
            name,
            key,
            id,
            owner,
            users,
            level,
        }
    }
}
