/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRoom {
    //
    #[serde(rename = "private_level", skip_serializing_if = "Option::is_none")]
    pub private_level: Option<models::RoomLevel>,
    // , deserialize_with = "Option::deserialize"
    #[serde(rename = "invite")]
    pub invite: Option<Vec<models::InviteWrapper>>,
    // , deserialize_with = "Option::deserialize"
    #[serde(rename = "key")]
    pub key: Option<String>,
}

impl UpdateRoom {
    pub fn new(invite: Option<Vec<models::InviteWrapper>>, key: Option<String>) -> UpdateRoom {
        UpdateRoom {
            private_level: None,
            invite,
            key,
        }
    }
}
