/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPrivate {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "user_type")]
    pub user_type: models::UserType,
    #[serde(rename = "appearance")]
    pub appearance: models::AppearancePublic,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl UserPrivate {
    pub fn new(
        username: String,
        user_type: models::UserType,
        appearance: models::AppearancePublic,
        id: uuid::Uuid,
    ) -> UserPrivate {
        UserPrivate {
            username,
            user_type,
            appearance,
            id,
        }
    }
}
