/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use strum::{Display, EnumIter};
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, EnumIter,
)] //, Display)]
#[derive(Default)]
pub enum UserType {
    #[serde(rename = "GUEST")]
    #[strum(to_string = "GUEST")]
    #[default]
    Guest,
    #[serde(rename = "PERMANENT")]
    #[strum(to_string = "PERMANENT")]
    Permanent,
    #[serde(rename = "SYSTEM")]
    #[strum(to_string = "SYSTEM")]
    System,
}

impl std::fmt::Display for UserType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Guest => write!(f, "GUEST"),
            Self::Permanent => write!(f, "PERMANENT"),
            Self::System => write!(f, "SYSTEM"),
        }
    }
}
