/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationError {
    //
    #[serde(rename = "loc")]
    pub loc: Vec<models::ValidationErrorLocInner>,
    //
    #[serde(rename = "msg")]
    pub msg: String,
    //
    #[serde(rename = "type")]
    pub r#type: String,
    //
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<serde_json::Value>,
    //
    #[serde(rename = "ctx", skip_serializing_if = "Option::is_none")]
    pub ctx: Option<serde_json::Value>,
}

impl ValidationError {
    pub fn new(
        loc: Vec<models::ValidationErrorLocInner>,
        msg: String,
        r#type: String,
    ) -> ValidationError {
        ValidationError {
            loc,
            msg,
            r#type,
            input: None,
            ctx: None,
        }
    }
}
