/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use futures_util::StreamExt;
use reqwest;
use reqwest_eventsource::{Error as EventError, Event, EventSource};
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`experimental_listen`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExperimentalListenError {
    Status401(models::ErrorModel),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`experimental_listen_static`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExperimentalListenStaticError {
    Status401(models::ErrorModel),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`experimental_send`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExperimentalSendError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`experimental_send_static`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExperimentalSendStaticError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rooms_random_room`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsRandomRoomError {
    UnknownValue(serde_json::Value),
}

pub async fn experimental_listen(
    configuration: &configuration::Configuration,
    room: &str,
) -> Result<(EventSource, Event), Error<ExperimentalListenError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;

    let uri_str = format!(
        "{}/r/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    match EventSource::new(req_builder) {
        Ok(mut es) => {
            if let Some(event) = es.next().await {
                return match event {
                    Ok(event) => Ok((es, event)),
                    Err(e) => Err(Error::ResponseError(ResponseContent {
                        status: reqwest::StatusCode::EXPECTATION_FAILED,
                        content: e.to_string(),
                        entity: None,
                    })),
                };
            } else {
                Err(Error::ResponseError(ResponseContent {
                    status: reqwest::StatusCode::EXPECTATION_FAILED,
                    content: "Connection Closed before event was sent".to_owned(),
                    entity: None,
                }))
            }
        }
        Err(e) => Err(Error::EventSourceError(e)),
    }
}

pub async fn experimental_listen_static(
    configuration: &configuration::Configuration,
    room: &str,
) -> Result<(EventSource, Event), Error<ExperimentalListenError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;

    let uri_str = format!(
        "{}/r/static/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    match EventSource::new(req_builder) {
        Ok(mut es) => {
            if let Some(event) = es.next().await {
                return match event {
                    Ok(event) => Ok((es, event)),
                    Err(e) => Err(Error::ResponseError(ResponseContent {
                        status: reqwest::StatusCode::EXPECTATION_FAILED,
                        content: e.to_string(),
                        entity: None,
                    })),
                };
            } else {
                Err(Error::ResponseError(ResponseContent {
                    status: reqwest::StatusCode::EXPECTATION_FAILED,
                    content: "Connection Closed before event was sent".to_owned(),
                    entity: None,
                }))
            }
        }
        Err(e) => Err(Error::EventSourceError(e)),
    }
}

pub async fn experimental_send(
    configuration: &configuration::Configuration,
    room: &str,
    message_send: models::MessageSend,
) -> Result<serde_json::Value, Error<ExperimentalSendError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;
    let p_body_message_send = message_send;

    let uri_str = format!(
        "{}/r/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_message_send);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `serde_json::Value`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExperimentalSendError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn experimental_send_static(
    configuration: &configuration::Configuration,
    room: &str,
    message_send: models::MessageSend,
) -> Result<serde_json::Value, Error<ExperimentalSendStaticError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;
    let p_body_message_send = message_send;

    let uri_str = format!(
        "{}/r/static/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_message_send);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `serde_json::Value`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExperimentalSendStaticError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn rooms_random_room(
    configuration: &configuration::Configuration,
) -> Result<serde_json::Value, Error<RoomsRandomRoomError>> {
    let uri_str = format!("{}/rooms/room", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `serde_json::Value`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RoomsRandomRoomError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
