/*
 * Console Chat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use futures_util::StreamExt;
use reqwest;
use reqwest_eventsource::{Error as EventError, *};
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`rooms_create_room`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsCreateRoomError {
    Status401(models::ErrorModel),
    Status409(models::ErrorModel),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rooms_delete_room`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsDeleteRoomError {
    Status401(models::ErrorModel),
    Status404(models::ErrorModel),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rooms_get_my_rooms`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsGetMyRoomsError {
    Status401(models::ErrorModel),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rooms_get_room`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsGetRoomError {
    Status401(models::ErrorModel),
    Status404(models::ErrorModel),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rooms_list_rooms`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsListRoomsError {
    Status401(models::ErrorModel),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rooms_listen`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsListenError {
    Status401(models::ErrorModel),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rooms_listen_static`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsListenStaticError {
    Status401(models::ErrorModel),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rooms_random_room`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsRandomRoomError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rooms_send`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsSendError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rooms_send_static`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsSendStaticError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rooms_update_room`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RoomsUpdateRoomError {
    Status401(models::ErrorModel),
    Status404(models::ErrorModel),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// Create a new room.  Args:     room (str): The name of the room to create.     user (PermanentUserDependency): The currently authenticated permanent user.     db (DatabaseDependency): The database dependency for executing queries.     room_data (CreateRoom): Data for the new room including private level and invited users.  Raises:     HTTPException: If the room already exists.  Returns:     StaticRoomPublic: The newly created room's public details.
pub async fn rooms_create_room(
    configuration: &configuration::Configuration,
    room: &str,
    create_room: models::CreateRoom,
) -> Result<serde_json::Value, Error<RoomsCreateRoomError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;
    let p_body_create_room = create_room;

    let uri_str = format!(
        "{}/rooms/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_room);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `serde_json::Value`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RoomsCreateRoomError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Delete an existing room.  Args:     room (str): The name of the room to delete.     user (PermanentUserDependency): The currently authenticated permanent user.     db (DatabaseDependency): The database dependency for executing queries.  Raises:     HTTPException: If the room does not exist or unauthorized access is attempted.
pub async fn rooms_delete_room(
    configuration: &configuration::Configuration,
    room: &str,
) -> Result<(), Error<RoomsDeleteRoomError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;

    let uri_str = format!(
        "{}/rooms/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RoomsDeleteRoomError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get all rooms owned by the current user.  Args:     user (PermanentUserDependency): The currently authenticated permanent user.     db (DatabaseDependency): The database dependency for executing queries.  Returns:     List[StaticRoomPublic]: A list of rooms owned by the user.
pub async fn rooms_get_my_rooms(
    configuration: &configuration::Configuration,
) -> Result<Vec<models::StaticRoomPublic>, Error<RoomsGetMyRoomsError>> {
    let uri_str = format!("{}/rooms/mine", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::StaticRoomPublic&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::StaticRoomPublic&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RoomsGetMyRoomsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn rooms_get_room(
    configuration: &configuration::Configuration,
    room: &str,
) -> Result<Vec<models::MessagePublic>, Error<RoomsGetRoomError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;

    let uri_str = format!(
        "{}/rooms/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::MessagePublic&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::MessagePublic&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RoomsGetRoomError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List all rooms.  Args:     db (DatabaseDependency): The database dependency for executing queries.  Returns:     List[StaticRoomPublic]: A list of public static room details.
pub async fn rooms_list_rooms(
    configuration: &configuration::Configuration,
) -> Result<Vec<models::StaticRoomPublic>, Error<RoomsListRoomsError>> {
    let uri_str = format!("{}/rooms/", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::StaticRoomPublic&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::StaticRoomPublic&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RoomsListRoomsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn rooms_listen(
    configuration: &configuration::Configuration,
    room: &str,
) -> Result<EventSource, Error<()>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;

    let uri_str = format!(
        "{}/r/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder.eventsource().map_err(Error::EventSourceError)
}

pub async fn rooms_listen_static(
    configuration: &configuration::Configuration,
    room: &str,
) -> Result<EventSource, Error<()>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;

    let uri_str = format!(
        "{}/r/static/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    req_builder.eventsource().map_err(Error::EventSourceError)
}

pub async fn rooms_random_room(
    configuration: &configuration::Configuration,
) -> Result<serde_json::Value, Error<RoomsRandomRoomError>> {
    let uri_str = format!("{}/rooms/room", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `serde_json::Value`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RoomsRandomRoomError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn rooms_send(
    configuration: &configuration::Configuration,
    room: &str,
    message_send: models::MessageSend,
) -> Result<serde_json::Value, Error<RoomsSendError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;
    let p_body_message_send = message_send;

    let uri_str = format!(
        "{}/room/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_message_send);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `serde_json::Value`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RoomsSendError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn rooms_send_static(
    configuration: &configuration::Configuration,
    room: &str,
    message_send: models::MessageSend,
) -> Result<serde_json::Value, Error<RoomsSendStaticError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;
    let p_body_message_send = message_send;

    let uri_str = format!(
        "{}/room/static/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_message_send);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `serde_json::Value`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RoomsSendStaticError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Update an existing room.  Args:     user (PermanentUserDependency): The currently authenticated permanent user.     db (DatabaseDependency): The database dependency for executing queries.     room (str): The name of the room to update.     room_data (UpdateRoom): Data for the updates, including private level, key, and invites.  Raises:     HTTPException: If the room does not exist or if unauthorized access is attempted.
pub async fn rooms_update_room(
    configuration: &configuration::Configuration,
    room: &str,
    update_room: models::UpdateRoom,
) -> Result<(), Error<RoomsUpdateRoomError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room = room;
    let p_body_update_room = update_room;

    let uri_str = format!(
        "{}/rooms/{room}",
        configuration.base_path,
        room = crate::apis::urlencode(p_path_room)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_room);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RoomsUpdateRoomError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
