# This file currently is for development
# it will get updated once the chat api works good enougth
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
  #  env_file:
  #    - .env
    ports:
      - "127.0.0.1:5432:5432"
      #- "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
      #- "6379:6379"
    volumes:
      - valkey_data:/data
    #networks:
      #- valkeynet
  #tuichat:
  #  # image: tuichat
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  networks:
  #    - valkeynet
  #  ports:
  #    - "8000:8000"
volumes:
  postgres_data:
    driver: local
  valkey_data:
    driver: local
networks:
  valkeynet:
    driver: bridge
